// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }

"use client";
import { useEffect } from "react";
import { useAuthStore } from "./lib/stores/authStore";
import "./globals.css";

function RootLayout({ children }: any) {
  const { checkAuth, signUp } = useAuthStore();

  useEffect(() => {
    checkAuth();
    const email = "changyong5899@gmail.com";
    const password = "boxUser";
    signUp(email, password);
  }, [checkAuth]);

  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}

export default RootLayout;
